---
ansible_connection: local
openshift_cluster_content:
- object: projects
  content:
  - name: create-the-cicd-project-namespace
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ playbook_dir }}/params/projectrequests/cicd-prod"
    tags:
      - cicd-namespaces
